azure:
  tenant_id: ${AZURE_TENANT_ID}
  client_id: ${AZURE_CLIENT_ID}
  client_secret: ${AZURE_CLIENT_SECRET}
  region: eastus

aws:
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-south-1

services:
  migrate:
    - cicd
    - iam
    - lambda
    - rds
    - s3
    #- ec2_instances
    #- vpc
github:
  personal_access_token: ${GITHUB_PERSONAL_ACCESS_TOKEN}
  repository: ${GITHUB_REPOSITORY}
  branch: ${GITHUB_BRANCH}
