instances:
  - name: optiflow-db-prod
    engine: postgres
    instance_class: db.t3.medium
    storage: 100
    storage_type: gp3
    username: optiflow_admin
    password: securePass123!
    backup_retention: 7
    multi_az: true
    public: false
    security_groups:
      - sg-0a1b2c3d4e5f6g7h8
    subnet_group: optiflow-subnet-group
    tags:
      Environment: production
      Project: OptiFlow
      Owner: Sunil

  - name: optiflow-db-dev
    engine: mysql
    instance_class: db.t3.micro
    storage: 20
    storage_type: gp2
    username: dev_admin
    password: devPass456!
    backup_retention: 3
    multi_az: false
    public: true
    security_groups:
      - sg-1a2b3c4d5e6f7g8h9
    subnet_group: optiflow-dev-subnet
    tags:
      Environment: development
      Project: OptiFlow
      Owner: Sunil